<?php
namespace Amvisie\Core\Web;

/**
 * Encapsulate data of option tags to be generated by HtmlHelper.
 * @author Ritesh Gite, <huestack@yahoo.com>
 */
class SelectOptionList
{
    
    private $dataArray;
    private $valueProperty, $captionProperty, $dataAttributeFields;
    
    private $hasObject;
    
    /**
     * Initializes new instance with specified data array and required properties.
     * @param array $dataArray An array of objects from data is retrieved.
     * @param string $valueProperty Name of property or key to get value for 'value' attribute.
     * @param type $captionProperty Name of property or key to get value for innerHTML of option tag.
     * @param array $dataAttributeFields An array containing name of properties or keys from where data attributes has to be generated.
     * @param bool $hasObject Helps determining that $dataArray has collection of objects or arrays.
     */
    public function __construct(
            array &$dataArray,
            string $valueProperty = 'Id',
            string $captionProperty = 'Name',
            array $dataAttributeFields = array(),
            bool $hasObject = false
        ) {

        $this->dataArray = $dataArray;
        $this->captionProperty = $captionProperty;
        $this->valueProperty = $valueProperty;
        
        if ($dataAttributeFields == null) {
            $dataAttributeFields = array();
        }
        
        $this->dataAttributeFields = $dataAttributeFields;
        $this->hasObject = $hasObject;
    }
    
    public function getValueProperty() : string
    {
        return $this->valueProperty;
    }
    
    public function getCaptionProperty() : string
    {
        return $this->captionProperty;
    }
    
    public function &getDataAttributeFields() : array
    {
        return $this->dataAttributeFields;
    }
    
    public function &getDataArray() : array
    {
        return $this->dataArray;
    }
    
    public function hasObjects() : bool
    {
        return $this->hasObject;
    }
}
